# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  #workflow_call:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn -B clean verify
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }} 
        labels: ${{ steps.meta.outputs.labels }}
        secrets: |
            "["+ DOCKER_USERNAME + "="+ secrets.DOCKER_USERNAME + "]",
            "["+ DOCKER_PASSWORD + "="+ secrets.DOCKERHUB_ACCESS_TOKEN + "]"
  #call-workflow:
  #  uses: jntcinco/chat-api/.github/workflows/docker-image.yml@master
  #call-workflow-in-local-repo:
  #  uses: ./.github/workflows/docker-image.yml
  #call-workflow-using-release:
  #  uses: jntcinco/chat-api/.github/workflows/docker-image.yml@v1
  #call-workflow-using-branch:
  #  uses: jntcinco/chat-api/.github/workflows/docker-image.yml@master   

