# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Startup Workflow

on:
  workflow_dispatch:

jobs:
  aws-secret-manager:
    runs-on: ubuntu-latest
    env:
      N_TEST_EXAMPLE: "Will be set from the keyvault."
      N_JAVA_HOME: "Will be set from the keyvault."
    steps:
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}
        
#      - name: Get AWS Secret
#        uses: aws-actions/aws-secretsmanager-get-secrets@v1
#        with:
#          secret-ids: |
#            AWS_SECRET, arn:aws:secretsmanager:ap-southeast-2:033376537995:secret:test/GithubAction/hello-kmEWfz
#          parse-json-secrets: true
#          N_TEST_EXAMPLE:  ${{ env.AWS_SECRET_TEST_EXAMPLE }}
#          N_JAVA_HOME: ${{ env.AWS_SECRET_JAVA_HOME }}
          
      - name: Get AWS Secret
        uses: jntcinco/chat-api/aws-secrets@tag-test
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          secrets: |
            AWS_SECRET, arn:aws:secretsmanager:ap-southeast-2:033376537995:secret:test/GithubAction/hello-kmEWfz
            
      - name: Print AWS Secrets
        run: |
          echo "Test Example 2: ${{ env.AWS_SECRET_TEST_EXAMPLE }}"
          echo "Java Home: ${{ env.AWS_SECRET_JAVA_HOME }}"
          
