# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Startup Workflow

on:
  workflow_dispatch:

jobs:
  aws-secret-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Get caller identity
        run: aws secretsmanager get-resource-policy \
             --secret-id test/GithubAction/hello
        
      - name: Get AWS Secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            arn:aws:secretsmanager:ap-southeast-2:033376537995:secret:test/GithubAction/hello-kmEWfz
            
      - name: Print AWS Secrets
        run: |
          echo "Test Example: ${{ env.TEST_EXAMPLE }}"
          echo "Java Home: ${{ env.JAVA_HOME }}"
          
      - name: Test output
        run: |
          echo "TEST_EXAMPLE: ${{ secrets.TEST_EXAMPLE }}"
          echo "JAVA_HOME: ${{ secrets.JAVA_HOME }}"
          
